version: 2.1
jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python manage.py test
    environment:
      - DJANGO_SETTINGS_MODULE=MySite.settings._base
      - PYTHONPATH=.
      - DOTENV_PATH=./.env
      - PYTHONUNBUFFERED=1
