version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    working_directory: /app
    steps:
      - checkout
          
      - run:
          name: Load environment variables
          command: |
            echo 'Loading environment variables...'
            export SECRET_KEY=$SECRET_KEY
      - run: pip install -r requirements.txt
      - run: python manage.py test
