# Generated by Django 3.2.16 on 2023-02-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230215_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='slug',
        ),
    ]
