# Generated by Django 4.1.5 on 2023-01-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="portfolio",
            options={"verbose_name": "Portfolio", "verbose_name_plural": "Portfolios"},
        ),
    ]
