# Generated by Django 4.1.5 on 2023-01-03 13:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_category_options_alter_portfolio_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="featured image"
            ),
        ),
    ]
