# Generated by Django 4.1.5 on 2023-01-03 13:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_portfolio_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="featured image"
            ),
        ),
    ]
